name: xSudo
main: _64FF00\xSudo\xSudo
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: 64FF00
description: Another USELESS plugin that allows the user to run commands as console or someone else.
website: https://github.com/64FF00/xSudo
permissions:
 xsudo.*:
  children:
   xsudo.console:
    description: Allows you to run commands as console.
   xsudo.user:
    description: Allows you to run commands as other users.
  